//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.2012
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunset.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sunset.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _07_calendar {
            get {
                object obj = ResourceManager.GetObject("_07_calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blackboard_128 {
            get {
                object obj = ResourceManager.GetObject("blackboard_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnAddCourse {
            get {
                object obj = ResourceManager.GetObject("btnAddCourse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnDeleteCourse {
            get {
                object obj = ResourceManager.GetObject("btnDeleteCourse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btndeletecourse_image {
            get {
                object obj = ResourceManager.GetObject("btndeletecourse_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;班級不排課時段&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;班級名稱,星期,開始時間&quot;&gt;
        ///            &lt;Field Name=&quot;班級名稱&quot; /&gt;
        ///			&lt;Field Name=&quot;星期&quot; /&gt;
        ///			&lt;Field Name=&quot;開始時間&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;	
        ///	&lt;Field Required=&quot;True&quot; Name=&quot;班級名稱&quot; Description=&quot;班級名稱&quot;&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ClassBusy {
            get {
                return ResourceManager.GetString("ClassBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;班級清單&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;班級名稱&quot;&gt;
        ///            &lt;Field Name=&quot;班級名稱&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;	
        ///	&lt;Field Required=&quot;True&quot; Name=&quot;班級名稱&quot; Description=&quot;班級的名稱&quot;&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ClassEx {
            get {
                return ResourceManager.GetString("ClassEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;班級不排課時段&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;班級名稱,星期,開始時間&quot;&gt;
        ///            &lt;Field Name=&quot;班級名稱&quot; /&gt;
        ///			&lt;Field Name=&quot;星期&quot; /&gt;
        ///			&lt;Field Name=&quot;開始時間&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;	
        ///	&lt;Field Required=&quot;True&quot; Name=&quot;班級名稱&quot; Description=&quot;班級名稱&quot;&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ClassExBusy {
            get {
                return ResourceManager.GetString("ClassExBusy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap classmate_128 {
            get {
                object obj = ResourceManager.GetObject("classmate_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap classmate_add_128 {
            get {
                object obj = ResourceManager.GetObject("classmate_add_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap classmate_add_32 {
            get {
                object obj = ResourceManager.GetObject("classmate_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap classroom_128 {
            get {
                object obj = ResourceManager.GetObject("classroom_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap classroom_down_128 {
            get {
                object obj = ResourceManager.GetObject("classroom_down_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;場地不排課時段&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;場地名稱,星期,開始時間&quot;&gt;
        ///            &lt;Field Name=&quot;場地名稱&quot; /&gt;
        ///	    &lt;Field Name=&quot;星期&quot; /&gt;
        ///	    &lt;Field Name=&quot;開始時間&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///	
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;場地名稱&quot; Description=&quot;場地名稱&quot;&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「場地名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ClassroomBusy {
            get {
                return ResourceManager.GetString("ClassroomBusy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap course_plan {
            get {
                object obj = ResourceManager.GetObject("course_plan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;課程排課資料&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;組合鍵值&quot;&gt;
        ///      &lt;Field Name=&quot;課程名稱&quot; /&gt;
        ///      &lt;Field Name=&quot;學年度&quot; /&gt;
        ///      &lt;Field Name=&quot;學期&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;課程名稱&quot; Description=&quot;課程名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///
        ///    &lt;Fi [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string CourseExtension {
            get {
                return ResourceManager.GetString("CourseExtension", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CourseIcon {
            get {
                object obj = ResourceManager.GetObject("CourseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;課程分段&quot;&gt;
        ///
        ///  &lt;DuplicateDetection&gt;
        ///
        ///  &lt;/DuplicateDetection&gt;
        ///
        ///  &lt;FieldList&gt;
        ///
        ///    &lt;!-- 必填欄位為課程名稱、學年度、學期及節數 --&gt;
        ///
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;課程名稱&quot; Description=&quot;課程名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學年度&quot; Description=&quot;學年度&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot;  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string CourseSection {
            get {
                return ResourceManager.GetString("CourseSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;DomainList&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;語文&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;數學&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;社會&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;自然與生活科技&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;健康與體育&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;藝術與人文&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;綜合活動&lt;/Domain&gt;
        ///	&lt;!-- &lt;Domain Type=&quot;Special&quot;&gt;實用語文&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;實用數學&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;社會適應&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;生活教育&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;休閒教育&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;職業 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string DefaultDomainList {
            get {
                return ResourceManager.GetString("DefaultDomainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;Ordinal&gt;
        ///	&lt;Subjects&gt;
        ///		&lt;Subject Name=&quot;國語文&quot; EnglishName=&quot;&quot; Order=&quot;1&quot;/&gt;
        ///		&lt;Subject Name=&quot;國文&quot; EnglishName=&quot;&quot; Order=&quot;2&quot;/&gt;
        ///		&lt;Subject Name=&quot;英文&quot; EnglishName=&quot;&quot; Order=&quot;3&quot;/&gt;
        ///		&lt;Subject Name=&quot;英語&quot; EnglishName=&quot;&quot; Order=&quot;4&quot;/&gt;
        ///		&lt;Subject Name=&quot;數學&quot; EnglishName=&quot;&quot; Order=&quot;5&quot;/&gt;
        ///		&lt;Subject Name=&quot;歷史&quot; EnglishName=&quot;&quot; Order=&quot;6&quot;/&gt;
        ///		&lt;Subject Name=&quot;地理&quot; EnglishName=&quot;&quot; Order=&quot;7&quot;/&gt;
        ///		&lt;Subject Name=&quot;公民&quot; EnglishName=&quot;&quot; Order=&quot;8&quot;/&gt;
        ///		&lt;Subject Name=&quot;理化&quot; EnglishName=&quot;&quot; Order=&quot;9&quot;/&gt;
        ///		&lt;Subject Name=&quot;生物&quot; EnglishName=&quot;&quot; Order=&quot;10&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string DefaultOrdinal {
            get {
                return ResourceManager.GetString("DefaultOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;Ordinal&gt;
        ///	&lt;Subjects&gt;
        ///		&lt;Subject Name=&quot;國語文&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;國文&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;英文&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;英語&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;數學&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;歷史&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;地理&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;公民&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;理化&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;生物&quot; EnglishName=&quot;&quot;/&gt;
        ///	&lt;/Subjects&gt;
        ///	&lt;Domains&gt;
        ///		&lt;Domain Name=&quot;語文&quot; EnglishName=&quot;&quot; Group=&quot;&quot;/&gt;
        ///		&lt;Domain Name=&quot;數學&quot; Engl [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string DefaultSubjectOrdinal {
            get {
                return ResourceManager.GetString("DefaultSubjectOrdinal", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap geometry_down_64 {
            get {
                object obj = ResourceManager.GetObject("geometry_down_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgClock {
            get {
                object obj = ResourceManager.GetObject("imgClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lesson_planning_128 {
            get {
                object obj = ResourceManager.GetObject("lesson_planning_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lesson_planning_down_128 {
            get {
                object obj = ResourceManager.GetObject("lesson_planning_down_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lesson_planning_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("lesson_planning_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;課程排課資料&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;組合鍵值&quot;&gt;
        ///            &lt;Field Name=&quot;課程名稱&quot; /&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;課程名稱&quot; Description=&quot;課程名稱&quot;&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validato [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Old_CourseExtension {
            get {
                return ResourceManager.GetString("Old_CourseExtension", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap program_plan_128 {
            get {
                object obj = ResourceManager.GetObject("program_plan_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sandglass_unlock_64 {
            get {
                object obj = ResourceManager.GetObject("sandglass_unlock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap schedule_128 {
            get {
                object obj = ResourceManager.GetObject("schedule_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap schedule_add_128 {
            get {
                object obj = ResourceManager.GetObject("schedule_add_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap schedule_add_64 {
            get {
                object obj = ResourceManager.GetObject("schedule_add_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap subject_add_128 {
            get {
                object obj = ResourceManager.GetObject("subject_add_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sunrise {
            get {
                object obj = ResourceManager.GetObject("sunrise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap teacher_128 {
            get {
                object obj = ResourceManager.GetObject("teacher_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;教師清單&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;教師姓名&quot;&gt;
        ///      &lt;Field Name=&quot;教師姓名&quot; /&gt;
        ///      &lt;Field Name=&quot;教師暱稱&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;教師姓名&quot; Description=&quot;教師的姓名&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field Required=&quot;False&quot; Name=&quot;教師 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string TeacherEx {
            get {
                return ResourceManager.GetString("TeacherEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;教師不排課時段&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;教師姓名,教師暱稱,星期,開始時間&quot;&gt;
        ///            &lt;Field Name=&quot;教師姓名&quot; /&gt;
        ///			&lt;Field Name=&quot;教師暱稱&quot; /&gt;
        ///			&lt;Field Name=&quot;星期&quot; /&gt;
        ///			&lt;Field Name=&quot;開始時間&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;	
        ///	&lt;Field Required=&quot;True&quot; Name=&quot;教師姓名&quot; Description=&quot;教師姓名&quot;&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師姓名」不允許空白。&quot; ErrorType=&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string TeacherExBusy {
            get {
                return ResourceManager.GetString("TeacherExBusy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap trainning_info_64 {
            get {
                object obj = ResourceManager.GetObject("trainning_info_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap virtualcurse_lock_128 {
            get {
                object obj = ResourceManager.GetObject("virtualcurse_lock_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap virtualcurse_unlock_128 {
            get {
                object obj = ResourceManager.GetObject("virtualcurse_unlock_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon warnClassName_Icon {
            get {
                object obj = ResourceManager.GetObject("warnClassName_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x_office_calendar {
            get {
                object obj = ResourceManager.GetObject("x_office_calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 偷來改的齒輪 {
            get {
                object obj = ResourceManager.GetObject("偷來改的齒輪", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] 功課表 {
            get {
                object obj = ResourceManager.GetObject("功課表", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 學生排課功課表 {
            get {
                object obj = ResourceManager.GetObject("學生排課功課表", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 學生排課功課表_欄位總表 {
            get {
                object obj = ResourceManager.GetObject("學生排課功課表_欄位總表", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
